import { blob, index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const benches = sqliteTable("benches", {
  rowId: integer("row_id").primaryKey({ autoIncrement: true }),
  id: text("id").notNull().unique(),
  osmType: text("osm_type").notNull(),
  osmId: integer("osm_id").notNull(),
  latitude: real("latitude").notNull(),
  longitude: real("longitude").notNull(),
  backrest: integer("backrest", { mode: "boolean" }),
  armrest: integer("armrest", { mode: "boolean" }),
  covered: integer("covered", { mode: "boolean" }),
  wheelchair: integer("wheelchair", { mode: "boolean" }),
  seats: integer("seats"),
  material: text("material"),
  directionDegrees: real("direction_degrees"),
  operator: text("operator"),
  description: text("description"),
  name: text("name"),
  dedication: text("dedication"),
  locationName: text("location_name"),
  locationKey: text("location_key"),
  locationPostcode: text("location_postcode"),
  locationCanton: text("location_canton"),
  createdByUserId: integer("created_by_user_id"),
  verificationStatus: text("verification_status").notNull().default("verified"),
  verifiedAt: text("verified_at"),
  removedAt: text("removed_at"),
  rawTags: text("raw_tags").notNull().default("{}"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  sourceUpdatedAt: text("source_updated_at").notNull(),
  importedAt: text("imported_at").notNull(),
}, (t) => [
  uniqueIndex("benches_osm_identity").on(t.osmType, t.osmId),
  index("benches_material_idx").on(t.material),
]);

export const benchEnrichments = sqliteTable("bench_enrichments", {
  benchRowId: integer("bench_row_id").primaryKey().references(() => benches.rowId, { onDelete: "cascade" }),
  elevationMeters: real("elevation_meters"),
  elevationSource: text("elevation_source"),
  elevationUpdatedAt: text("elevation_updated_at"),
  inForest: integer("in_forest", { mode: "boolean" }),
  canopyPercent: real("canopy_percent"),
  distanceForestMeters: real("distance_forest_meters"),
  distanceWaterMeters: real("distance_water_meters"),
  distancePathMeters: real("distance_path_meters"),
  distanceMajorRoadMeters: real("distance_major_road_meters"),
  horizonProfile: text("horizon_profile"),
  terrainHorizonProfile: text("terrain_horizon_profile"),
  obstructionTypes: text("obstruction_types"),
  obstructionDistances: text("obstruction_distances"),
  buildingObstructionPercent: real("building_obstruction_percent"),
  vegetationObstructionPercent: real("vegetation_obstruction_percent"),
  distanceBuildingMeters: real("distance_building_meters"),
  buildingCount100m: integer("building_count_100m"),
  sunMinutesSummer: integer("sun_minutes_summer"),
  sunMinutesWinter: integer("sun_minutes_winter"),
  sunMinutesSpring: integer("sun_minutes_spring"),
  sunMinutesAutumn: integer("sun_minutes_autumn"),
  sunConfidence: text("sun_confidence").notNull().default("niedrig"),
  viewScore: real("view_score"),
  viewConfidence: text("view_confidence").notNull().default("niedrig"),
  viewComponents: text("view_components"),
  viewLabels: text("view_labels"),
  viewSectors: text("view_sectors"),
  contextSourceVersion: text("context_source_version"),
  landContext: text("land_context"),
  waterfront: integer("waterfront", { mode: "boolean" }),
  canopyContext: text("canopy_context"),
  canopyShare3m: real("canopy_share_3m"),
  canopyShare10m: real("canopy_share_10m"),
  canopyShare25m: real("canopy_share_25m"),
  vegetationMedianHeight: real("vegetation_median_height"),
  vegetationMaxHeight: real("vegetation_max_height"),
  environmentComputedAt: text("environment_computed_at"),
  pipelineVersion: text("pipeline_version"),
  computedAt: text("computed_at"),
});

export const ratings = sqliteTable("ratings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  benchRowId: integer("bench_row_id").notNull().references(() => benches.rowId, { onDelete: "cascade" }),
  contributorHash: text("contributor_hash").notNull(),
  overall: integer("overall").notNull(),
  view: integer("view_score").notNull(),
  comfort: integer("comfort").notNull(),
  quiet: integer("quiet").notNull(),
  note: text("note"),
  visible: integer("visible", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  userId: integer("user_id"),
}, (t) => [uniqueIndex("ratings_one_per_contributor").on(t.benchRowId, t.contributorHash)]);

export const corrections = sqliteTable("corrections", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  benchRowId: integer("bench_row_id").notNull().references(() => benches.rowId, { onDelete: "cascade" }),
  contributorHash: text("contributor_hash").notNull(),
  field: text("field").notNull(),
  proposedValue: text("proposed_value").notNull(),
  note: text("note"),
  visible: integer("visible", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull(),
});

export const imageObservations = sqliteTable("image_observations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  provider: text("provider").notNull(),
  providerImageId: text("provider_image_id").notNull(),
  captureGroupId: text("capture_group_id").notNull(),
  sourceUrl: text("source_url").notNull(),
  fetchUrl: text("fetch_url").notNull(),
  latitude: real("latitude").notNull(),
  longitude: real("longitude").notNull(),
  heading: real("heading"),
  capturedAt: text("captured_at"),
  author: text("author"),
  license: text("license"),
  imageSha256: text("image_sha256"),
  analysisStatus: text("analysis_status").notNull().default("pending"),
  relevanceProbability: real("relevance_probability"),
  predictions: text("predictions"),
  modelVersion: text("model_version"),
  promptVersion: text("prompt_version"),
  analyzedAt: text("analyzed_at"),
  attempts: integer("attempts").notNull().default(0),
  lastError: text("last_error"),
  discoveredAt: text("discovered_at").notNull(),
}, (t) => [
  uniqueIndex("image_observations_identity").on(t.provider, t.providerImageId),
  index("image_observations_status_idx").on(t.analysisStatus, t.discoveredAt),
]);

export const benchImageEvidence = sqliteTable("bench_image_evidence", {
  benchRowId: integer("bench_row_id").notNull().references(() => benches.rowId, { onDelete: "cascade" }),
  imageObservationId: integer("image_observation_id").notNull().references(() => imageObservations.id, { onDelete: "cascade" }),
  distanceMeters: real("distance_meters").notNull(),
  directViewEligible: integer("direct_view_eligible", { mode: "boolean" }).notNull().default(false),
  evidenceWeight: real("evidence_weight").notNull().default(1),
});

export const benchLikelyMetadata = sqliteTable("bench_likely_metadata", {
  benchRowId: integer("bench_row_id").primaryKey().references(() => benches.rowId, { onDelete: "cascade" }),
  landContext: text("land_context"),
  landContextProbability: real("land_context_probability"),
  canopyContext: text("canopy_context"),
  canopyProbability: real("canopy_probability"),
  lakeViewProbability: real("lake_view_probability"),
  mountainViewProbability: real("mountain_view_probability"),
  openViewProbability: real("open_view_probability"),
  limitedViewProbability: real("limited_view_probability"),
  buildingsProbability: real("buildings_probability"),
  roadRailProbability: real("road_rail_probability"),
  confidence: text("confidence").notNull().default("low"),
  evidenceGroupCount: integer("evidence_group_count").notNull().default(0),
  evidenceSummary: text("evidence_summary").notNull().default("[]"),
  modelVersion: text("model_version"),
  reconcilerVersion: text("reconciler_version").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const environmentFeatures = sqliteTable("environment_features", {
  rowId: integer("row_id").primaryKey({ autoIncrement: true }),
  source: text("source").notNull(),
  sourceId: text("source_id").notNull(),
  kind: text("kind").notNull(),
  subtype: text("subtype"),
  centerLatitude: real("center_latitude").notNull(),
  centerLongitude: real("center_longitude").notNull(),
  minLatitude: real("min_latitude").notNull(),
  maxLatitude: real("max_latitude").notNull(),
  minLongitude: real("min_longitude").notNull(),
  maxLongitude: real("max_longitude").notNull(),
  heightMeters: real("height_meters"),
  rawTags: text("raw_tags").notNull().default("{}"),
  importedAt: text("imported_at").notNull(),
  geometryWkb: blob("geometry_wkb", { mode: "buffer" }),
  geometryCrs: integer("geometry_crs").notNull().default(2056),
  sourceVersion: text("source_version"),
  sourceUpdatedAt: text("source_updated_at"),
}, (t) => [uniqueIndex("environment_source_identity").on(t.source, t.sourceId, t.kind)]);

export const landCoverFeatures = sqliteTable("land_cover_features", {
  rowId: integer("row_id").primaryKey({ autoIncrement: true }),
  source: text("source").notNull(),
  sourceId: text("source_id").notNull(),
  class: text("class").notNull(),
  geometryWkb: blob("geometry_wkb", { mode: "buffer" }).notNull(),
  geometryCrs: integer("geometry_crs").notNull().default(2056),
  minLatitude: real("min_latitude").notNull(),
  maxLatitude: real("max_latitude").notNull(),
  minLongitude: real("min_longitude").notNull(),
  maxLongitude: real("max_longitude").notNull(),
  sourceVersion: text("source_version").notNull(),
  sourceUpdatedAt: text("source_updated_at"),
  importedAt: text("imported_at").notNull(),
}, (t) => [uniqueIndex("land_cover_source_identity").on(t.source, t.sourceId, t.class)]);
