import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const benches = sqliteTable("benches", {
  rowId: integer("row_id").primaryKey({ autoIncrement: true }),
  id: text("id").notNull().unique(),
  osmType: text("osm_type").notNull(),
  osmId: integer("osm_id").notNull(),
  latitude: real("latitude").notNull(),
  longitude: real("longitude").notNull(),
  backrest: integer("backrest", { mode: "boolean" }),
  armrest: integer("armrest", { mode: "boolean" }),
  covered: integer("covered", { mode: "boolean" }),
  wheelchair: integer("wheelchair", { mode: "boolean" }),
  seats: integer("seats"),
  material: text("material"),
  directionDegrees: real("direction_degrees"),
  operator: text("operator"),
  description: text("description"),
  rawTags: text("raw_tags").notNull().default("{}"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  sourceUpdatedAt: text("source_updated_at").notNull(),
  importedAt: text("imported_at").notNull(),
}, (t) => [
  uniqueIndex("benches_osm_identity").on(t.osmType, t.osmId),
  index("benches_material_idx").on(t.material),
]);

export const benchEnrichments = sqliteTable("bench_enrichments", {
  benchRowId: integer("bench_row_id").primaryKey().references(() => benches.rowId, { onDelete: "cascade" }),
  elevationMeters: real("elevation_meters"),
  elevationSource: text("elevation_source"),
  elevationUpdatedAt: text("elevation_updated_at"),
  inForest: integer("in_forest", { mode: "boolean" }),
  canopyPercent: real("canopy_percent"),
  distanceForestMeters: real("distance_forest_meters"),
  distanceWaterMeters: real("distance_water_meters"),
  distancePathMeters: real("distance_path_meters"),
  distanceMajorRoadMeters: real("distance_major_road_meters"),
  horizonProfile: text("horizon_profile"),
  terrainHorizonProfile: text("terrain_horizon_profile"),
  obstructionTypes: text("obstruction_types"),
  obstructionDistances: text("obstruction_distances"),
  buildingObstructionPercent: real("building_obstruction_percent"),
  vegetationObstructionPercent: real("vegetation_obstruction_percent"),
  distanceBuildingMeters: real("distance_building_meters"),
  buildingCount100m: integer("building_count_100m"),
  sunMinutesSummer: integer("sun_minutes_summer"),
  sunMinutesWinter: integer("sun_minutes_winter"),
  sunMinutesSpring: integer("sun_minutes_spring"),
  sunMinutesAutumn: integer("sun_minutes_autumn"),
  sunConfidence: text("sun_confidence").notNull().default("niedrig"),
  viewScore: real("view_score"),
  viewConfidence: text("view_confidence").notNull().default("niedrig"),
  viewComponents: text("view_components"),
  viewLabels: text("view_labels"),
  viewSectors: text("view_sectors"),
  contextSourceVersion: text("context_source_version"),
  pipelineVersion: text("pipeline_version"),
  computedAt: text("computed_at"),
});

export const ratings = sqliteTable("ratings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  benchRowId: integer("bench_row_id").notNull().references(() => benches.rowId, { onDelete: "cascade" }),
  contributorHash: text("contributor_hash").notNull(),
  overall: integer("overall").notNull(),
  view: integer("view_score").notNull(),
  comfort: integer("comfort").notNull(),
  quiet: integer("quiet").notNull(),
  note: text("note"),
  visible: integer("visible", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (t) => [uniqueIndex("ratings_one_per_contributor").on(t.benchRowId, t.contributorHash)]);

export const corrections = sqliteTable("corrections", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  benchRowId: integer("bench_row_id").notNull().references(() => benches.rowId, { onDelete: "cascade" }),
  contributorHash: text("contributor_hash").notNull(),
  field: text("field").notNull(),
  proposedValue: text("proposed_value").notNull(),
  note: text("note"),
  visible: integer("visible", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull(),
});
