// Generated by scripts/generate-dialect-packs.ts. Do not edit.
import p0 from "./generated/gsw-basel.json";
import p1 from "./generated/gsw-baselbiet.json";
import p2 from "./generated/gsw-northwest.json";
import p3 from "./generated/gsw-bern.json";
import p4 from "./generated/gsw-bern-oberland.json";
import p5 from "./generated/gsw-sensler.json";
import p6 from "./generated/gsw-jaun.json";
import p7 from "./generated/gsw-zurich.json";
import p8 from "./generated/gsw-schaffhausen.json";
import p9 from "./generated/gsw-luzern.json";
import p10 from "./generated/gsw-entlebuch.json";
import p11 from "./generated/gsw-zug-schwyz.json";
import p12 from "./generated/gsw-muotathal.json";
import p13 from "./generated/gsw-obwalden.json";
import p14 from "./generated/gsw-nidwalden.json";
import p15 from "./generated/gsw-uri.json";
import p16 from "./generated/gsw-glarus.json";
import p17 from "./generated/gsw-sg-city.json";
import p18 from "./generated/gsw-rheintal.json";
import p19 from "./generated/gsw-toggenburg.json";
import p20 from "./generated/gsw-southeast.json";
import p21 from "./generated/gsw-thurgau.json";
import p22 from "./generated/gsw-appenzell.json";
import p23 from "./generated/gsw-wallis.json";
import p24 from "./generated/gsw-buendner.json";
import p25 from "./generated/gsw-walser.json";
import p26 from "./generated/bar-samnaun.json";
import p27 from "./generated/rm-sursilvan.json";
import p28 from "./generated/rm-sutsilvan.json";
import p29 from "./generated/rm-surmiran.json";
import p30 from "./generated/rm-puter.json";
import p31 from "./generated/rm-vallader.json";
import p32 from "./generated/frp-west.json";
import p33 from "./generated/frp-alpine.json";
import p34 from "./generated/frc-jura.json";
import p35 from "./generated/lmo-alpine.json";
import p36 from "./generated/lmo-prealpine.json";
import p37 from "./generated/lmo-lowland.json";

export const DIALECT_PACK_MESSAGES = {
  "gsw-basel": p0,
  "gsw-baselbiet": p1,
  "gsw-northwest": p2,
  "gsw-bern": p3,
  "gsw-bern-oberland": p4,
  "gsw-sensler": p5,
  "gsw-jaun": p6,
  "gsw-zurich": p7,
  "gsw-schaffhausen": p8,
  "gsw-luzern": p9,
  "gsw-entlebuch": p10,
  "gsw-zug-schwyz": p11,
  "gsw-muotathal": p12,
  "gsw-obwalden": p13,
  "gsw-nidwalden": p14,
  "gsw-uri": p15,
  "gsw-glarus": p16,
  "gsw-sg-city": p17,
  "gsw-rheintal": p18,
  "gsw-toggenburg": p19,
  "gsw-southeast": p20,
  "gsw-thurgau": p21,
  "gsw-appenzell": p22,
  "gsw-wallis": p23,
  "gsw-buendner": p24,
  "gsw-walser": p25,
  "bar-samnaun": p26,
  "rm-sursilvan": p27,
  "rm-sutsilvan": p28,
  "rm-surmiran": p29,
  "rm-puter": p30,
  "rm-vallader": p31,
  "frp-west": p32,
  "frp-alpine": p33,
  "frc-jura": p34,
  "lmo-alpine": p35,
  "lmo-prealpine": p36,
  "lmo-lowland": p37,
} as const;
