// Generated by scripts/generate-dialect-packs.ts. Do not edit.
export const DIALECT_PACK_MANIFEST = [
  {
    "id": "gsw-basel",
    "label": "Baseldytsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-basel-default-1",
        "text": "Do kasch di grad e bitzli härehogge."
      },
      {
        "id": "gsw-basel-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nit berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nit bekannt."
    },
    "sources": [
      {
        "id": "basel-dictionary",
        "title": "Rudolf Suter: digitized Baseldeutsch dictionary",
        "url": "https://baseldeutsch-woerterbuch.floatleft.ch/woerterbuch/"
      }
    ]
  },
  {
    "id": "gsw-baselbiet",
    "label": "Baselbieter Dialäkt",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-baselbiet-default-1",
        "text": "Do chasch di grad ane setze und chli verschnuufe."
      },
      {
        "id": "gsw-baselbiet-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "sds",
        "title": "Sprachatlas der deutschen Schweiz",
        "url": "https://sprachatlas.ch/"
      }
    ]
  },
  {
    "id": "gsw-northwest",
    "label": "Nordwestschwiizerisch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-northwest-default-1",
        "text": "Do chasch di grad ane setze und chli verschnuufe."
      },
      {
        "id": "gsw-northwest-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "solothurn",
        "title": "Matthias Friedli: Eigenart der Solothurner Dialekte",
        "url": "https://solothurner.mundartverein.ch/eigenart-der-solothurner-dialekte/"
      },
      {
        "id": "aargau",
        "title": "SRF: dialectologist Hans-Peter Schifferle on Aargau regions",
        "url": "https://www.srf.ch/news/aargau-solothurn-raetselraten-woher-kommt-diese-aargauerin"
      }
    ]
  },
  {
    "id": "gsw-bern",
    "label": "Bärndütsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-bern-default-1",
        "text": "Da chasch di häreha, für es bitzli z verschnuufe."
      },
      {
        "id": "gsw-bern-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "bern-writing",
        "title": "Berndeutsch.ch: Schrybe",
        "url": "https://www.berndeutsch.ch/pages/schrybe"
      }
    ]
  },
  {
    "id": "gsw-bern-oberland",
    "label": "Bärner Oberländer Dialäkt",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-bern-oberland-default-1",
        "text": "Hock di häre und lueg e chli i d Wält."
      },
      {
        "id": "gsw-bern-oberland-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "sds",
        "title": "Sprachatlas der deutschen Schweiz",
        "url": "https://sprachatlas.ch/"
      },
      {
        "id": "bern-writing",
        "title": "Berndeutsch.ch: Schrybe",
        "url": "https://www.berndeutsch.ch/pages/schrybe"
      }
    ]
  },
  {
    "id": "gsw-sensler",
    "label": "Seislertütsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-sensler-default-1",
        "text": "Muusdǜri? Hie chasch hǜbscheli häresitze ù ggùgge."
      },
      {
        "id": "gsw-sensler-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nit berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nit bekannt."
    },
    "sources": [
      {
        "id": "sensler-glossary",
        "title": "Christian Schmutz: Seisler glossary",
        "url": "https://senslerhotline.ch/seisler/glossar/"
      },
      {
        "id": "sensler-state",
        "title": "State of Fribourg: Kenntnis und Pflege des Senslerdeutschen",
        "url": "https://www.fr.ch/de/culture-et-tourisme/tradifri/kenntnis-und-pflege-des-senslerdeutschen"
      }
    ]
  },
  {
    "id": "gsw-jaun",
    "label": "Jùutütsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-jaun-default-1",
        "text": "Hock di es Momänt häre und verschnuuf."
      },
      {
        "id": "gsw-jaun-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nit berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nit bekannt."
    },
    "sources": [
      {
        "id": "jaun",
        "title": "Leo Buchs: Jaundeutsches Wörterbuch, publisher page",
        "url": "https://www.kund.ch/produkt/jaundeutsches-woerterbuch"
      }
    ]
  },
  {
    "id": "gsw-zurich",
    "label": "Züridütsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-zurich-default-1",
        "text": "Da chasch di grad anesetze, zum es bitzli verschnuufe."
      },
      {
        "id": "gsw-zurich-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "zurich",
        "title": "Zürich tourism: Zürichdeutsch",
        "url": "https://www.zuerich.com/de/informieren-planen/nuetzliche-infos-und-services/zuerichdeutsch"
      }
    ]
  },
  {
    "id": "gsw-schaffhausen",
    "label": "Schafuuser Mundart",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-schaffhausen-default-1",
        "text": "Do chasch di in Rueh anesetze."
      },
      {
        "id": "gsw-schaffhausen-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "schaffhausen",
        "title": "Verein für die Schaffhauser Mundart: books",
        "url": "https://mundartschaffhausen.ch/buecher/"
      }
    ]
  },
  {
    "id": "gsw-luzern",
    "label": "Lozärnerdütsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-luzern-default-1",
        "text": "Hock ab und schnuf es bitzli dure."
      },
      {
        "id": "gsw-luzern-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "luzern",
        "title": "Luzerner Fasnachtskomitee: local written usage",
        "url": "https://www.lfk.ch/"
      }
    ]
  },
  {
    "id": "gsw-entlebuch",
    "label": "Äntlibuecher Dialäkt",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-entlebuch-default-1",
        "text": "Hock di häre, s pressiert nüd."
      },
      {
        "id": "gsw-entlebuch-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "sds",
        "title": "Sprachatlas der deutschen Schweiz",
        "url": "https://sprachatlas.ch/"
      }
    ]
  },
  {
    "id": "gsw-zug-schwyz",
    "label": "Zuger und Schwyzer Mundart",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-zug-schwyz-default-1",
        "text": "Da chasch di häresitze und chli uusruäbe."
      },
      {
        "id": "gsw-zug-schwyz-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "sds",
        "title": "Sprachatlas der deutschen Schweiz",
        "url": "https://sprachatlas.ch/"
      }
    ]
  },
  {
    "id": "gsw-muotathal",
    "label": "Muotathaler Dialäkt",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-muotathal-default-1",
        "text": "Hock di häre und plodärä oder gnüüss d Rueh."
      },
      {
        "id": "gsw-muotathal-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "muotathal",
        "title": "Muotathaler Wörterbuch: sauft and related examples",
        "url": "https://dialekt.muotathal.ch/search/sauft"
      },
      {
        "id": "muotathal-sun",
        "title": "Muotathaler Wörterbuch: Schii",
        "url": "https://dialekt.muotathal.ch/search/Schii"
      }
    ]
  },
  {
    "id": "gsw-obwalden",
    "label": "Obwaldner Mundart",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-obwalden-default-1",
        "text": "Hie chasch äs Schutzli ghirmä."
      },
      {
        "id": "gsw-obwalden-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "kerns",
        "title": "Municipality of Kerns: Mundartwörter on benches",
        "url": "https://www.kerns.ch/_doc/1443095"
      }
    ]
  },
  {
    "id": "gsw-nidwalden",
    "label": "Nidwaldner Mundart",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-nidwalden-default-1",
        "text": "Mach der's kommod und hock ab."
      },
      {
        "id": "gsw-nidwalden-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "nidwalden",
        "title": "Holebänz: Nidwaldner Ausdrücke",
        "url": "https://holebaenz.ch/nidwaldner-ausdruecke/"
      }
    ]
  },
  {
    "id": "gsw-uri",
    "label": "Urner Mundart",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-uri-default-1",
        "text": "Hock di häre – für hüt isch baschta."
      },
      {
        "id": "gsw-uri-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "uri",
        "title": "Lucerne tourism: interview with Felix Aschwanden about Urner dialect",
        "url": "https://blog.luzern.com/typisch-urner-dialekt/"
      }
    ]
  },
  {
    "id": "gsw-glarus",
    "label": "Glarnerdütsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-glarus-default-1",
        "text": "Hock ab, aber bloss nöd weidli."
      },
      {
        "id": "gsw-glarus-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "glarus",
        "title": "ESAF 2025 Glarnerland+: Glarner glossary",
        "url": "https://esaf2025.ch/glossar/"
      },
      {
        "id": "glarus-dictionary",
        "title": "Glarner Mundartverein",
        "url": "https://glarner.mundartverein.ch/"
      }
    ]
  },
  {
    "id": "gsw-sg-city",
    "label": "Sanggaller Mundart",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-sg-city-default-1",
        "text": "Do chasch di anesetze und e chli verschnuufe."
      },
      {
        "id": "gsw-sg-city-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "sg-city",
        "title": "SRF: Susan Osterwalder-Brändle on Hopp Sanggale!",
        "url": "https://www.srf.ch/news/st-galler-dialekt-3-000-st-galler-woerter-gesammelt"
      }
    ]
  },
  {
    "id": "gsw-rheintal",
    "label": "Rhiitaler Mundart",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-rheintal-default-1",
        "text": "Do chasch rüabìg rööschta."
      },
      {
        "id": "gsw-rheintal-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "diepoldsau",
        "title": "Diepoldsau municipality: dialect and local literature",
        "url": "https://www.diepoldsau.ch/diepoldsau/portraet/dialekt.html/21"
      },
      {
        "id": "diep-dictionary",
        "title": "Tippìlzouar und Schmeattar Dialekt: dictionary",
        "url": "https://www.diepoldsau.ch/public/upload/assets/1383/W%C3%B6rterbuch.pdf?fp=1"
      },
      {
        "id": "werdenberg",
        "title": "Doazmol: Frümsner Dialekt-Ausdrücke",
        "url": "https://www.doazmol.ch/frumsner-dialekt-ausdrucke"
      }
    ]
  },
  {
    "id": "gsw-toggenburg",
    "label": "Toggeburger Dialäkt",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-toggenburg-default-1",
        "text": "Hock di ane und mach emol Pause."
      },
      {
        "id": "gsw-toggenburg-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "toggenburg",
        "title": "Region Toggenburg: Memo-Spiel zum Toggenburger Dialekt",
        "url": "https://www.toggenburg.ch/de/aktuell/detail-seite/memo-spiel-zum-toggenburger-dialekt/"
      }
    ]
  },
  {
    "id": "gsw-southeast",
    "label": "Südostschwiizerisch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-southeast-default-1",
        "text": "Do chasch di grad anesetze."
      },
      {
        "id": "gsw-southeast-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "sds",
        "title": "Sprachatlas der deutschen Schweiz",
        "url": "https://sprachatlas.ch/"
      }
    ]
  },
  {
    "id": "gsw-thurgau",
    "label": "Thurgauer Mundart",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-thurgau-default-1",
        "text": "Do chasch di härehocke und chli sii."
      },
      {
        "id": "gsw-thurgau-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "thurgau",
        "title": "Martin Hannes Graf: Thurgauer Mundart in Geschichte und Gegenwart (2014)",
        "url": "https://www.napoleonturm-hohenrain.ch/app/download/12576876893/Thurgauer%2BMundart%2B-%2BM.%2BGraf.pdf?t=1767890971"
      }
    ]
  },
  {
    "id": "gsw-appenzell",
    "label": "Appenzeller Dialäkt",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-appenzell-default-1",
        "text": "Hock di bezli häre und chnooz emol nöd."
      },
      {
        "id": "gsw-appenzell-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nöd berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nöd bekannt."
    },
    "sources": [
      {
        "id": "appenzell-ai",
        "title": "Appenzellerdialekt.ch: dialect glossary",
        "url": "https://appenzellerdialekt.ch/"
      },
      {
        "id": "appenzell-ar",
        "title": "Staatsarchiv AR: Heinrich Altherr book project",
        "url": "https://query-staatsarchiv.ar.ch/archivplansuche.aspx?ID=617020"
      }
    ]
  },
  {
    "id": "gsw-wallis",
    "label": "Wallisertiitsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-wallis-default-1",
        "text": "Da chasch di es Bizji häreheie und verschnuufu."
      },
      {
        "id": "gsw-wallis-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nit berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nit bekannt."
    },
    "sources": [
      {
        "id": "wallis-lexicon",
        "title": "Volmar Schmid: Walliser dialect lexicon, R",
        "url": "https://www.walliserdialekt.ch/r"
      },
      {
        "id": "wallis-writing",
        "title": "Anleitung zur Schreibweise: Walliser dialect",
        "url": "https://www.walliserdialekt.ch/anleitung-zur-schreibweise"
      }
    ]
  },
  {
    "id": "gsw-buendner",
    "label": "Bündnerdütsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-buendner-default-1",
        "text": "Do chasch di grad anesitza und a Wili verschnuufa."
      },
      {
        "id": "gsw-buendner-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nid berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nid bekannt."
    },
    "sources": [
      {
        "id": "buendner-word",
        "title": "Bergün Filisur tourism: Patschifig eis go neh",
        "url": "https://www.berguen-filisur.graubuenden.ch/de/winter/patschifig-eis-go-neh"
      },
      {
        "id": "sds",
        "title": "Sprachatlas der deutschen Schweiz",
        "url": "https://sprachatlas.ch/"
      }
    ]
  },
  {
    "id": "gsw-walser",
    "label": "Walserdütsch",
    "language": "de",
    "languageTag": "gsw-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "gsw-walser-default-1",
        "text": "Hock di häre und rüew e Wili."
      },
      {
        "id": "gsw-walser-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nit berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nit bekannt."
    },
    "sources": [
      {
        "id": "walser",
        "title": "Internationale Vereinigung für Walsertum: Sprache",
        "url": "https://www.wir-walser.ch/die-walser/sprache"
      },
      {
        "id": "walser-books",
        "title": "Walserverein Graubünden: book catalogue",
        "url": "https://shop.walserverein-gr.ch/Buecher/"
      },
      {
        "id": "bosco",
        "title": "Native lexicographer interview: Gurinerdeutsch",
        "url": "https://www.beobachter.ch/gesellschaft/wattarhuat-chlaptuachtschi-co-so-will-eine-tessinerin-das-bedrohte-gurinerdeutsch"
      }
    ]
  },
  {
    "id": "bar-samnaun",
    "label": "Samnaunerisch",
    "language": "de",
    "languageTag": "bar-CH",
    "formatLocale": "de-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "bar-samnaun-default-1",
        "text": "Hock di her und rast a bissl."
      },
      {
        "id": "bar-samnaun-default-2",
        "text": "S Bänkli het Zyt – und du hoffentlich au."
      }
    ],
    "light": {
      "potentialSun": "Direkte Sunne möglich; Bewölkung nit berücksichtigt.",
      "shade": "Berechneter Schatte.",
      "night": "Nacht: kei direkte Sunne.",
      "unknown": "Lichtsituation no nit bekannt."
    },
    "sources": [
      {
        "id": "samnaun",
        "title": "Samnaun: Die Sprache der Samnauner",
        "url": "https://www.samnaun.swiss/"
      }
    ]
  },
  {
    "id": "rm-sursilvan",
    "label": "Sursilvan",
    "language": "rm",
    "languageTag": "rm-CH",
    "formatLocale": "rm-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "rm-sursilvan-default-1",
        "text": "Cheu sas ti seser in mument e trer flad."
      },
      {
        "id": "rm-sursilvan-default-2",
        "text": "Il banc ha peda – e ti speranza er."
      }
    ],
    "light": {
      "potentialSun": "Glisch directa dal sulegl pussaivla; nivels betg resguardads.",
      "shade": "Sumbriva calculada.",
      "night": "Notg: nagina glisch directa dal sulegl.",
      "unknown": "La situaziun da glisch n’è anc betg enconuschenta."
    },
    "sources": [
      {
        "id": "romansh",
        "title": "Lia Rumantscha: The Romansh",
        "url": "https://www.liarumantscha.ch/en/romansh/romansh"
      },
      {
        "id": "romansh-regions",
        "title": "Disentis Sedrun: Rhaeto-Romanic",
        "url": "https://www.andermatt-sedrun-disentis.ch/disentis-sedrun/en/stories/romontsch"
      },
      {
        "id": "rm-phrase",
        "title": "Chattà: Rumantsch Grischun text collection",
        "url": "https://xn--chatt-vqa.ch/creschids?Sposition=1937"
      }
    ]
  },
  {
    "id": "rm-sutsilvan",
    "label": "Sutsilvan",
    "language": "rm",
    "languageTag": "rm-CH",
    "formatLocale": "rm-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "rm-sutsilvan-default-1",
        "text": "Qua pos ti seser en mument e trer flad."
      },
      {
        "id": "rm-sutsilvan-default-2",
        "text": "Il banc ha peda – e ti speranza er."
      }
    ],
    "light": {
      "potentialSun": "Glisch directa dal sulegl pussaivla; nivels betg resguardads.",
      "shade": "Sumbriva calculada.",
      "night": "Notg: nagina glisch directa dal sulegl.",
      "unknown": "La situaziun da glisch n’è anc betg enconuschenta."
    },
    "sources": [
      {
        "id": "romansh",
        "title": "Lia Rumantscha: The Romansh",
        "url": "https://www.liarumantscha.ch/en/romansh/romansh"
      },
      {
        "id": "romansh-regions",
        "title": "Disentis Sedrun: Rhaeto-Romanic",
        "url": "https://www.andermatt-sedrun-disentis.ch/disentis-sedrun/en/stories/romontsch"
      },
      {
        "id": "rm-phrase",
        "title": "Chattà: Rumantsch Grischun text collection",
        "url": "https://xn--chatt-vqa.ch/creschids?Sposition=1937"
      }
    ]
  },
  {
    "id": "rm-surmiran",
    "label": "Surmiran",
    "language": "rm",
    "languageTag": "rm-CH",
    "formatLocale": "rm-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "rm-surmiran-default-1",
        "text": "Cò post te seser en mument e trer flad."
      },
      {
        "id": "rm-surmiran-default-2",
        "text": "Il banc ha peda – e ti speranza er."
      }
    ],
    "light": {
      "potentialSun": "Glisch directa dal sulegl pussaivla; nivels betg resguardads.",
      "shade": "Sumbriva calculada.",
      "night": "Notg: nagina glisch directa dal sulegl.",
      "unknown": "La situaziun da glisch n’è anc betg enconuschenta."
    },
    "sources": [
      {
        "id": "romansh",
        "title": "Lia Rumantscha: The Romansh",
        "url": "https://www.liarumantscha.ch/en/romansh/romansh"
      },
      {
        "id": "romansh-regions",
        "title": "Disentis Sedrun: Rhaeto-Romanic",
        "url": "https://www.andermatt-sedrun-disentis.ch/disentis-sedrun/en/stories/romontsch"
      },
      {
        "id": "rm-phrase",
        "title": "Chattà: Rumantsch Grischun text collection",
        "url": "https://xn--chatt-vqa.ch/creschids?Sposition=1937"
      }
    ]
  },
  {
    "id": "rm-puter",
    "label": "Puter",
    "language": "rm",
    "languageTag": "rm-CH",
    "formatLocale": "rm-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "rm-puter-default-1",
        "text": "Cò poust tü tschanter ün mumaint e trer il flà."
      },
      {
        "id": "rm-puter-default-2",
        "text": "Il banc ha peda – e ti speranza er."
      }
    ],
    "light": {
      "potentialSun": "Glisch directa dal sulegl pussaivla; nivels betg resguardads.",
      "shade": "Sumbriva calculada.",
      "night": "Notg: nagina glisch directa dal sulegl.",
      "unknown": "La situaziun da glisch n’è auncha betg enconuschenta."
    },
    "sources": [
      {
        "id": "romansh",
        "title": "Lia Rumantscha: The Romansh",
        "url": "https://www.liarumantscha.ch/en/romansh/romansh"
      },
      {
        "id": "romansh-regions",
        "title": "Disentis Sedrun: Rhaeto-Romanic",
        "url": "https://www.andermatt-sedrun-disentis.ch/disentis-sedrun/en/stories/romontsch"
      },
      {
        "id": "rm-phrase",
        "title": "Chattà: Rumantsch Grischun text collection",
        "url": "https://xn--chatt-vqa.ch/creschids?Sposition=1937"
      }
    ]
  },
  {
    "id": "rm-vallader",
    "label": "Vallader",
    "language": "rm",
    "languageTag": "rm-CH",
    "formatLocale": "rm-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "rm-vallader-default-1",
        "text": "Qua poust tü tschantar ün mumaint e trar il flà."
      },
      {
        "id": "rm-vallader-default-2",
        "text": "Il banc ha peda – e ti speranza er."
      }
    ],
    "light": {
      "potentialSun": "Glisch directa dal sulegl pussaivla; nivels betg resguardads.",
      "shade": "Sumbriva calculada.",
      "night": "Notg: nagina glisch directa dal sulegl.",
      "unknown": "La situaziun da glisch n’è amo betg enconuschenta."
    },
    "sources": [
      {
        "id": "romansh",
        "title": "Lia Rumantscha: The Romansh",
        "url": "https://www.liarumantscha.ch/en/romansh/romansh"
      },
      {
        "id": "romansh-regions",
        "title": "Disentis Sedrun: Rhaeto-Romanic",
        "url": "https://www.andermatt-sedrun-disentis.ch/disentis-sedrun/en/stories/romontsch"
      },
      {
        "id": "rm-phrase",
        "title": "Chattà: Rumantsch Grischun text collection",
        "url": "https://xn--chatt-vqa.ch/creschids?Sposition=1937"
      }
    ]
  },
  {
    "id": "frp-west",
    "label": "Patois romand occidental",
    "language": "fr",
    "languageTag": "frp-CH",
    "formatLocale": "fr-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "frp-west-default-1",
        "text": "Ique, te pou te reposâ on moment."
      },
      {
        "id": "frp-west-default-2",
        "text": "Lo banc at tot son temps."
      }
    ],
    "light": {
      "potentialSun": "Soleil direct possible ; nuages non pris en compte.",
      "shade": "Ombre prévue par le calcul.",
      "night": "Nuit : pas de soleil direct.",
      "unknown": "Situation lumineuse encore inconnue."
    },
    "sources": [
      {
        "id": "gpsr",
        "title": "University of Neuchâtel: Glossaire des patois de la Suisse romande",
        "url": "https://www.unine.ch/isla/glossaire-des-patois-de-la-suisse-romande-gpsr/"
      },
      {
        "id": "romand-historical",
        "title": "Bridel / Favrat: Glossaire du patois de la Suisse romande (1866)",
        "url": "https://www.shsr.ch/mdr/MDR21_02.html"
      }
    ]
  },
  {
    "id": "frp-alpine",
    "label": "Francoprovençal alpin",
    "language": "fr",
    "languageTag": "frp-CH",
    "formatLocale": "fr-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "frp-alpine-default-1",
        "text": "Arrête-tè on moment; les montagnes ant tot lor temps."
      },
      {
        "id": "frp-alpine-default-2",
        "text": "Lo banc at tot son temps."
      }
    ],
    "light": {
      "potentialSun": "Soleil direct possible ; nuages non pris en compte.",
      "shade": "Ombre prévue par le calcul.",
      "night": "Nuit : pas de soleil direct.",
      "unknown": "Situation lumineuse encore inconnue."
    },
    "sources": [
      {
        "id": "gpsr",
        "title": "University of Neuchâtel: Glossaire des patois de la Suisse romande",
        "url": "https://www.unine.ch/isla/glossaire-des-patois-de-la-suisse-romande-gpsr/"
      },
      {
        "id": "romand-historical",
        "title": "Bridel / Favrat: Glossaire du patois de la Suisse romande (1866)",
        "url": "https://www.shsr.ch/mdr/MDR21_02.html"
      }
    ]
  },
  {
    "id": "frc-jura",
    "label": "Parler jurassien",
    "language": "fr",
    "languageTag": "fr-CH",
    "formatLocale": "fr-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "frc-jura-default-1",
        "text": "Pose-tè ci; lo banc ne s'en va pe."
      },
      {
        "id": "frc-jura-default-2",
        "text": "Lo banc at tot son temps."
      }
    ],
    "light": {
      "potentialSun": "Soleil direct possible ; nuages non pris en compte.",
      "shade": "Ombre prévue par le calcul.",
      "night": "Nuit : pas de soleil direct.",
      "unknown": "Situation lumineuse encore inconnue."
    },
    "sources": [
      {
        "id": "gpsr",
        "title": "University of Neuchâtel: Glossaire des patois de la Suisse romande",
        "url": "https://www.unine.ch/isla/glossaire-des-patois-de-la-suisse-romande-gpsr/"
      },
      {
        "id": "romand-historical",
        "title": "Bridel / Favrat: Glossaire du patois de la Suisse romande (1866)",
        "url": "https://www.shsr.ch/mdr/MDR21_02.html"
      }
    ]
  },
  {
    "id": "lmo-alpine",
    "label": "Lombard alpin",
    "language": "it",
    "languageTag": "lmo-CH",
    "formatLocale": "it-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "lmo-alpine-default-1",
        "text": "Chì te pödet sentàss on moment e tirà ol fiaa."
      },
      {
        "id": "lmo-alpine-default-2",
        "text": "La banchina la gh'ha minga pressa."
      }
    ],
    "light": {
      "potentialSun": "Sole diretto possibile; nuvole non considerate.",
      "shade": "Ombra prevista dal calcolo.",
      "night": "Notte: niente sole diretto.",
      "unknown": "Situazione luminosa ancora sconosciuta."
    },
    "sources": [
      {
        "id": "cde",
        "title": "Canton Ticino: Centro di dialettologia e di etnografia",
        "url": "https://www4.ti.ch/decs/dcsu/cde/cde"
      }
    ]
  },
  {
    "id": "lmo-prealpine",
    "label": "Dialett ticines prealpin",
    "language": "it",
    "languageTag": "lmo-CH",
    "formatLocale": "it-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "lmo-prealpine-default-1",
        "text": "Chì ta pö setat giò un mument e tirà 'l fiaa."
      },
      {
        "id": "lmo-prealpine-default-2",
        "text": "La banchina la gh'ha minga pressa."
      }
    ],
    "light": {
      "potentialSun": "Sole diretto possibile; nuvole non considerate.",
      "shade": "Ombra prevista dal calcolo.",
      "night": "Notte: niente sole diretto.",
      "unknown": "Situazione luminosa ancora sconosciuta."
    },
    "sources": [
      {
        "id": "cde",
        "title": "Canton Ticino: Centro di dialettologia e di etnografia",
        "url": "https://www4.ti.ch/decs/dcsu/cde/cde"
      }
    ]
  },
  {
    "id": "lmo-lowland",
    "label": "Dialett dal Sottoceneri",
    "language": "it",
    "languageTag": "lmo-CH",
    "formatLocale": "it-CH",
    "version": "2026.09.1",
    "invitations": [
      {
        "id": "lmo-lowland-default-1",
        "text": "Fermat un mument: 'l post al gh'ha minga pressa."
      },
      {
        "id": "lmo-lowland-default-2",
        "text": "La banchina la gh'ha minga pressa."
      }
    ],
    "light": {
      "potentialSun": "Sole diretto possibile; nuvole non considerate.",
      "shade": "Ombra prevista dal calcolo.",
      "night": "Notte: niente sole diretto.",
      "unknown": "Situazione luminosa ancora sconosciuta."
    },
    "sources": [
      {
        "id": "cde",
        "title": "Canton Ticino: Centro di dialettologia e di etnografia",
        "url": "https://www4.ti.ch/decs/dcsu/cde/cde"
      }
    ]
  }
] as const;
export const DIALECT_AREAS = [
  {
    "id": "bs-city",
    "label": "Basel-Stadt / Baseldeutsch",
    "group": "Northwest",
    "anchors": [
      "Basel",
      "Riehen",
      "Bettingen"
    ],
    "parentPackId": "gsw-basel",
    "sourceIds": [
      "basel-dictionary",
      "sds"
    ],
    "variants": [
      {
        "id": "gsw-basel-rest-1",
        "text": "Hogg di ane und mach e bitzli Pause. S pressiert jo nit."
      }
    ]
  },
  {
    "id": "bl-lower",
    "label": "Unteres Baselbiet / Birstal",
    "group": "Northwest",
    "anchors": [
      "Muttenz",
      "Pratteln",
      "Reinach BL",
      "Aesch BL"
    ],
    "parentPackId": "gsw-baselbiet",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "bl-upper",
    "label": "Oberes Baselbiet",
    "group": "Northwest",
    "anchors": [
      "Sissach",
      "Gelterkinden",
      "Waldenburg"
    ],
    "parentPackId": "gsw-baselbiet",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "bl-laufental",
    "label": "Laufental",
    "group": "Northwest",
    "anchors": [
      "Laufen",
      "Zwingen"
    ],
    "parentPackId": "gsw-baselbiet",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "so-schwarzbuben",
    "label": "Schwarzbubenland",
    "group": "Northwest",
    "anchors": [
      "Dornach",
      "Breitenbach",
      "Büsserach"
    ],
    "parentPackId": "gsw-northwest",
    "sourceIds": [
      "solothurn"
    ],
    "variants": []
  },
  {
    "id": "so-core",
    "label": "Solothurn core / Jurasüdfuss",
    "group": "Northwest",
    "anchors": [
      "Solothurn",
      "Grenchen",
      "Balsthal"
    ],
    "parentPackId": "gsw-northwest",
    "sourceIds": [
      "solothurn"
    ],
    "variants": [
      {
        "id": "gsw-solothurn-rest-1",
        "text": "Hock di häre. Es pressiert nit."
      }
    ]
  },
  {
    "id": "so-niederamt",
    "label": "Olten / Niederamt",
    "group": "Northwest",
    "anchors": [
      "Olten",
      "Schönenwerd",
      "Niedergösgen"
    ],
    "parentPackId": "gsw-northwest",
    "sourceIds": [
      "solothurn"
    ],
    "variants": []
  },
  {
    "id": "so-bucheggberg",
    "label": "Bucheggberg",
    "group": "Northwest",
    "anchors": [
      "Buchegg",
      "Lüterswil"
    ],
    "parentPackId": "gsw-northwest",
    "sourceIds": [
      "solothurn"
    ],
    "variants": []
  },
  {
    "id": "ag-fricktal",
    "label": "Fricktal",
    "group": "Northwest",
    "anchors": [
      "Frick",
      "Rheinfelden",
      "Laufenburg AG"
    ],
    "parentPackId": "gsw-northwest",
    "sourceIds": [
      "aargau"
    ],
    "variants": []
  },
  {
    "id": "ag-west",
    "label": "Westlicher / Berner Aargau",
    "group": "Northwest",
    "anchors": [
      "Aarau",
      "Zofingen",
      "Unterkulm"
    ],
    "parentPackId": "gsw-northwest",
    "sourceIds": [
      "aargau"
    ],
    "variants": []
  },
  {
    "id": "ag-east",
    "label": "Östlicher Aargau",
    "group": "Northwest",
    "anchors": [
      "Baden",
      "Wettingen",
      "Zurzach"
    ],
    "parentPackId": "gsw-northwest",
    "sourceIds": [
      "aargau"
    ],
    "variants": []
  },
  {
    "id": "ag-freiamt",
    "label": "Freiamt",
    "group": "Northwest",
    "anchors": [
      "Muri AG",
      "Wohlen AG",
      "Sins"
    ],
    "parentPackId": "gsw-northwest",
    "sourceIds": [
      "aargau"
    ],
    "variants": []
  },
  {
    "id": "be-mittelland",
    "label": "Berner Mittelland",
    "group": "Bern / Fribourg",
    "anchors": [
      "Bern",
      "Köniz",
      "Münsingen"
    ],
    "parentPackId": "gsw-bern",
    "sourceIds": [
      "bern-writing",
      "sds"
    ],
    "variants": [
      {
        "id": "gsw-bern-rest-1",
        "text": "Hie muesch nid jufle. Hock di häre u verschnuuf e chli."
      }
    ]
  },
  {
    "id": "be-emmental",
    "label": "Emmental",
    "group": "Bern / Fribourg",
    "anchors": [
      "Langnau im Emmental",
      "Trub",
      "Sumiswald"
    ],
    "parentPackId": "gsw-bern",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-oberaargau",
    "label": "Oberaargau",
    "group": "Bern / Fribourg",
    "anchors": [
      "Langenthal",
      "Herzogenbuchsee",
      "Huttwil"
    ],
    "parentPackId": "gsw-bern",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-seeland",
    "label": "Berner Seeland",
    "group": "Bern / Fribourg",
    "anchors": [
      "Lyss",
      "Aarberg",
      "Ins",
      "Erlach"
    ],
    "parentPackId": "gsw-bern",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "fr-seeland",
    "label": "Deutschfreiburger Seeland",
    "group": "Bern / Fribourg",
    "anchors": [
      "Murten/Morat",
      "Kerzers",
      "Ried bei Kerzers"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "sensler-state",
      "fribourg-diversity",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "fr-sensler",
    "label": "Senslerdeutsch / Seislertütsch",
    "group": "Bern / Fribourg",
    "anchors": [
      "Düdingen",
      "Tafers",
      "Schmitten FR",
      "Bösingen",
      "Wünnewil",
      "Flamatt",
      "Ueberstorf",
      "Heitenried",
      "St. Ursen",
      "St. Silvester",
      "Rechthalten",
      "Brünisried",
      "Tentlingen",
      "Giffers",
      "Plaffeien",
      "Plasselb",
      "Alterswil",
      "St. Antoni",
      "Oberschrot",
      "Zumholz"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "sensler-state",
      "sensler-glossary"
    ],
    "variants": [
      {
        "id": "gsw-sensler-rest-1",
        "text": "Muusdǜri? Hie chasch hǜbscheli häresitze ù ggùgge."
      }
    ]
  },
  {
    "id": "fr-gurmels-contact",
    "label": "Gurmels contact area",
    "group": "Bern / Fribourg",
    "anchors": [
      "Gurmels",
      "Kleingurmels"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "sensler-state",
      "swisstopo"
    ],
    "variants": []
  },
  {
    "id": "fr-jaun",
    "label": "Jaundeutsch / Jùutütsch",
    "group": "Bern / Fribourg",
    "anchors": [
      "Jaun",
      "Im Fang"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "jaun",
      "fribourg-diversity"
    ],
    "variants": []
  },
  {
    "id": "fr-city-contact",
    "label": "Fribourg/Freiburg multilingual urban contact",
    "group": "Bern / Fribourg",
    "anchors": [
      "Fribourg/Freiburg",
      "Basse-Ville/Unterstadt"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "sensler-state",
      "fribourg-diversity"
    ],
    "variants": []
  },
  {
    "id": "be-biel-contact",
    "label": "Biel/Bienne bilingual city",
    "group": "Bern / Fribourg",
    "anchors": [
      "Biel/Bienne"
    ],
    "parentPackId": "gsw-bern",
    "sourceIds": [
      "sds",
      "gpsr"
    ],
    "variants": []
  },
  {
    "id": "be-thun",
    "label": "Thun and adjoining Oberland foothills",
    "group": "Bernese Oberland",
    "anchors": [
      "Thun",
      "Steffisburg",
      "Sigriswil"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-boedeli",
    "label": "Bödeli",
    "group": "Bernese Oberland",
    "anchors": [
      "Interlaken",
      "Unterseen",
      "Matten bei Interlaken"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-brienz",
    "label": "Brienz",
    "group": "Bernese Oberland",
    "anchors": [
      "Brienz",
      "Schwanden bei Brienz"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-hasli",
    "label": "Haslital",
    "group": "Bernese Oberland",
    "anchors": [
      "Meiringen",
      "Innertkirchen",
      "Guttannen",
      "Gadmen"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-grindelwald",
    "label": "Grindelwald",
    "group": "Bernese Oberland",
    "anchors": [
      "Grindelwald"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-lauterbrunnen",
    "label": "Lauterbrunnental",
    "group": "Bernese Oberland",
    "anchors": [
      "Lauterbrunnen",
      "Wengen",
      "Mürren",
      "Stechelberg"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-frutig",
    "label": "Frutigland",
    "group": "Bernese Oberland",
    "anchors": [
      "Frutigen",
      "Adelboden",
      "Kandersteg"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-simmental",
    "label": "Simmental",
    "group": "Bernese Oberland",
    "anchors": [
      "Zweisimmen",
      "Lenk",
      "Diemtigen",
      "Erlenbach im Simmental"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "be-saanen",
    "label": "Saanenland",
    "group": "Bernese Oberland",
    "anchors": [
      "Saanen",
      "Gstaad",
      "Lauenen",
      "Gsteig"
    ],
    "parentPackId": "gsw-bern-oberland",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "zh-core",
    "label": "Zürich city / central canton",
    "group": "Zürich / Schaffhausen",
    "anchors": [
      "Zürich",
      "Uster",
      "Horgen"
    ],
    "parentPackId": "gsw-zurich",
    "sourceIds": [
      "sds",
      "zurich"
    ],
    "variants": [
      {
        "id": "gsw-zurich-rest-1",
        "text": "Hock e chli ab. Nöd alles mues grad sofort sii."
      }
    ]
  },
  {
    "id": "zh-north",
    "label": "Zürcher Weinland / Rafzerfeld",
    "group": "Zürich / Schaffhausen",
    "anchors": [
      "Andelfingen",
      "Rafz",
      "Marthalen"
    ],
    "parentPackId": "gsw-zurich",
    "sourceIds": [
      "sds",
      "zurich"
    ],
    "variants": []
  },
  {
    "id": "zh-oberland",
    "label": "Zürcher Oberland",
    "group": "Zürich / Schaffhausen",
    "anchors": [
      "Wald ZH",
      "Fischenthal",
      "Bauma"
    ],
    "parentPackId": "gsw-zurich",
    "sourceIds": [
      "sds",
      "zurich"
    ],
    "variants": []
  },
  {
    "id": "sh-city",
    "label": "Schaffhausen city / surrounding area",
    "group": "Zürich / Schaffhausen",
    "anchors": [
      "Schaffhausen",
      "Neuhausen am Rheinfall"
    ],
    "parentPackId": "gsw-schaffhausen",
    "sourceIds": [
      "sds",
      "schaffhausen"
    ],
    "variants": []
  },
  {
    "id": "sh-klettgau",
    "label": "Schaffhauser Klettgau",
    "group": "Zürich / Schaffhausen",
    "anchors": [
      "Hallau",
      "Wilchingen",
      "Osterfingen",
      "Schleitheim"
    ],
    "parentPackId": "gsw-schaffhausen",
    "sourceIds": [
      "sds",
      "schaffhausen"
    ],
    "variants": []
  },
  {
    "id": "sh-reiat",
    "label": "Reiat",
    "group": "Zürich / Schaffhausen",
    "anchors": [
      "Thayngen",
      "Lohn SH",
      "Stetten SH"
    ],
    "parentPackId": "gsw-schaffhausen",
    "sourceIds": [
      "sds",
      "schaffhausen"
    ],
    "variants": []
  },
  {
    "id": "sh-stein",
    "label": "Stein / upper Rhine",
    "group": "Zürich / Schaffhausen",
    "anchors": [
      "Stein am Rhein",
      "Ramsen",
      "Buch SH"
    ],
    "parentPackId": "gsw-schaffhausen",
    "sourceIds": [
      "sds",
      "schaffhausen"
    ],
    "variants": []
  },
  {
    "id": "lu-core",
    "label": "Luzern city / central Mittelland",
    "group": "Central Switzerland",
    "anchors": [
      "Luzern",
      "Kriens",
      "Emmen"
    ],
    "parentPackId": "gsw-luzern",
    "sourceIds": [
      "sds",
      "luzern"
    ],
    "variants": [
      {
        "id": "gsw-luzern-rest-1",
        "text": "E chli Pause tuet rüüdig guet."
      }
    ]
  },
  {
    "id": "lu-entlebuch",
    "label": "Entlebuch",
    "group": "Central Switzerland",
    "anchors": [
      "Schüpfheim",
      "Entlebuch",
      "Escholzmatt",
      "Marbach LU",
      "Flühli"
    ],
    "parentPackId": "gsw-entlebuch",
    "sourceIds": [
      "sds",
      "luzern"
    ],
    "variants": []
  },
  {
    "id": "lu-hinterland",
    "label": "Luzerner Hinterland / northwest",
    "group": "Central Switzerland",
    "anchors": [
      "Willisau",
      "Zell LU",
      "Reiden"
    ],
    "parentPackId": "gsw-luzern",
    "sourceIds": [
      "sds",
      "luzern"
    ],
    "variants": []
  },
  {
    "id": "lu-seetal",
    "label": "Luzerner Seetal",
    "group": "Central Switzerland",
    "anchors": [
      "Hochdorf",
      "Hitzkirch",
      "Ballwil"
    ],
    "parentPackId": "gsw-luzern",
    "sourceIds": [
      "sds",
      "luzern"
    ],
    "variants": []
  },
  {
    "id": "zg-core",
    "label": "Zug",
    "group": "Central Switzerland",
    "anchors": [
      "Zug",
      "Baar",
      "Cham",
      "Menzingen"
    ],
    "parentPackId": "gsw-zug-schwyz",
    "sourceIds": [
      "sds"
    ],
    "variants": []
  },
  {
    "id": "sz-core",
    "label": "Schwyz basin",
    "group": "Central Switzerland",
    "anchors": [
      "Schwyz",
      "Steinen",
      "Arth"
    ],
    "parentPackId": "gsw-zug-schwyz",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "sz-einsiedeln",
    "label": "Einsiedeln / Alpthal",
    "group": "Central Switzerland",
    "anchors": [
      "Einsiedeln",
      "Alpthal",
      "Rothenthurm"
    ],
    "parentPackId": "gsw-zug-schwyz",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "sz-march-hoefe",
    "label": "March / Höfe",
    "group": "Central Switzerland",
    "anchors": [
      "Lachen",
      "Schübelbach",
      "Wollerau",
      "Feusisberg"
    ],
    "parentPackId": "gsw-zug-schwyz",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "sz-muotathal",
    "label": "Muotathal / Bisisthal",
    "group": "Central Switzerland",
    "anchors": [
      "Muotathal",
      "Bisisthal",
      "Ried SZ"
    ],
    "parentPackId": "gsw-muotathal",
    "sourceIds": [
      "muotathal",
      "muotathal-sun"
    ],
    "variants": [
      {
        "id": "gsw-muotathal-rest-1",
        "text": "Da chasch ä chli plodärä oder eifach Pause machä."
      }
    ]
  },
  {
    "id": "ow-sarnen-kerns",
    "label": "Sarneraatal, Kerns writing model",
    "group": "Central Switzerland",
    "anchors": [
      "Kerns",
      "Sarnen",
      "Sachseln",
      "Alpnach",
      "Giswil"
    ],
    "parentPackId": "gsw-obwalden",
    "sourceIds": [
      "kerns",
      "sds"
    ],
    "variants": [
      {
        "id": "gsw-kerns-rest-1",
        "text": "Da chasch äs Schutzli ghirmä."
      }
    ]
  },
  {
    "id": "ow-lungern",
    "label": "Lungern",
    "group": "Central Switzerland",
    "anchors": [
      "Lungern"
    ],
    "parentPackId": "gsw-obwalden",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "ow-engelberg",
    "label": "Engelberg",
    "group": "Central Switzerland",
    "anchors": [
      "Engelberg"
    ],
    "parentPackId": "gsw-obwalden",
    "sourceIds": [
      "sds",
      "dialektatlas"
    ],
    "variants": []
  },
  {
    "id": "nw-core",
    "label": "Nidwalden",
    "group": "Central Switzerland",
    "anchors": [
      "Stans",
      "Buochs",
      "Ennetbürgen",
      "Beckenried",
      "Dallenwil",
      "Wolfenschiessen"
    ],
    "parentPackId": "gsw-nidwalden",
    "sourceIds": [
      "nidwalden",
      "sds"
    ],
    "variants": [
      {
        "id": "gsw-nidwalden-rest-1",
        "text": "Mach s der kommod und bliib no chli."
      }
    ]
  },
  {
    "id": "ur-reuss",
    "label": "Uri main Reuss valley and adjoining valleys",
    "group": "Central Switzerland",
    "anchors": [
      "Altdorf",
      "Bürglen UR",
      "Erstfeld",
      "Silenen",
      "Gurtnellen",
      "Isenthal",
      "Unterschächen"
    ],
    "parentPackId": "gsw-uri",
    "sourceIds": [
      "uri",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "ur-urseren",
    "label": "Urseren",
    "group": "Central Switzerland",
    "anchors": [
      "Andermatt",
      "Hospental",
      "Realp"
    ],
    "parentPackId": "gsw-uri",
    "sourceIds": [
      "uri"
    ],
    "variants": [
      {
        "id": "gsw-urseren-rest-1",
        "text": "Baschta mit Juflä. Etz git s ä Pause."
      }
    ]
  },
  {
    "id": "gl-north",
    "label": "Glarus North / Kerenzen",
    "group": "Glarus",
    "anchors": [
      "Näfels",
      "Mollis",
      "Niederurnen",
      "Obstalden",
      "Filzbach"
    ],
    "parentPackId": "gsw-glarus",
    "sourceIds": [
      "glarus",
      "glarus-dictionary",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gl-central",
    "label": "Glarus central valley",
    "group": "Glarus",
    "anchors": [
      "Glarus",
      "Ennenda",
      "Netstal"
    ],
    "parentPackId": "gsw-glarus",
    "sourceIds": [
      "glarus",
      "glarus-dictionary",
      "sds"
    ],
    "variants": [
      {
        "id": "gsw-glarus-rest-1",
        "text": "Da chasch e chli nügge. S mues nöd alles weidli gaa."
      }
    ]
  },
  {
    "id": "gl-linth",
    "label": "Upper Linth valley",
    "group": "Glarus",
    "anchors": [
      "Schwanden",
      "Linthal",
      "Rüti GL",
      "Braunwald"
    ],
    "parentPackId": "gsw-glarus",
    "sourceIds": [
      "glarus",
      "glarus-dictionary",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gl-sernf",
    "label": "Sernftal",
    "group": "Glarus",
    "anchors": [
      "Engi",
      "Matt",
      "Elm"
    ],
    "parentPackId": "gsw-glarus",
    "sourceIds": [
      "glarus",
      "glarus-dictionary",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "sg-city",
    "label": "St. Gallen city / Fürstenland",
    "group": "Eastern Switzerland",
    "anchors": [
      "St. Gallen",
      "Gossau SG",
      "Flawil",
      "Uzwil"
    ],
    "parentPackId": "gsw-sg-city",
    "sourceIds": [
      "sg-city",
      "thurgau"
    ],
    "variants": [
      {
        "id": "gsw-sg-city-rest-1",
        "text": "Nüd lang bibääbele: Hock ab und mach e chli Pause."
      }
    ]
  },
  {
    "id": "sg-rheintal-north",
    "label": "St. Galler Rheintal: northern contact belt",
    "group": "Eastern Switzerland",
    "anchors": [
      "Rheineck",
      "St. Margrethen",
      "Au SG",
      "Heerbrugg",
      "Berneck",
      "Balgach"
    ],
    "parentPackId": "gsw-rheintal",
    "sourceIds": [
      "sds",
      "thurgau",
      "diepoldsau"
    ],
    "variants": []
  },
  {
    "id": "sg-rheintal-upper",
    "label": "St. Galler Rheintal: central / southern belt",
    "group": "Eastern Switzerland",
    "anchors": [
      "Altstätten",
      "Rebstein",
      "Marbach SG",
      "Oberriet",
      "Eichberg",
      "Rüthi"
    ],
    "parentPackId": "gsw-rheintal",
    "sourceIds": [
      "sds",
      "diepoldsau"
    ],
    "variants": []
  },
  {
    "id": "sg-diepoldsau",
    "label": "Diepoldsau / Schmitter",
    "group": "Eastern Switzerland",
    "anchors": [
      "Diepoldsau",
      "Schmitter"
    ],
    "parentPackId": "gsw-rheintal",
    "sourceIds": [
      "diepoldsau",
      "diep-dictionary"
    ],
    "variants": [
      {
        "id": "gsw-diepoldsau-rest-1",
        "text": "Do chasch röschta. Mach s rüabìg."
      }
    ]
  },
  {
    "id": "sg-werdenberg",
    "label": "Werdenberg",
    "group": "Eastern Switzerland",
    "anchors": [
      "Sennwald",
      "Frümsen",
      "Sax",
      "Salez",
      "Buchs SG",
      "Grabs",
      "Gams",
      "Sevelen",
      "Wartau"
    ],
    "parentPackId": "gsw-rheintal",
    "sourceIds": [
      "werdenberg",
      "sds"
    ],
    "variants": [
      {
        "id": "gsw-werdenberg-fruemsner-rest-1",
        "text": "Mach s hofeli. Do chasch e chli verwiila."
      }
    ]
  },
  {
    "id": "sg-togg-lower",
    "label": "Lower / middle Toggenburg",
    "group": "Eastern Switzerland",
    "anchors": [
      "Bütschwil",
      "Lichtensteig",
      "Wattwil",
      "Kirchberg SG"
    ],
    "parentPackId": "gsw-toggenburg",
    "sourceIds": [
      "toggenburg",
      "sds"
    ],
    "variants": [
      {
        "id": "gsw-toggenburg-rest-1",
        "text": "Etz isch Ziit för e Pause. Alles andere chonnt nochher."
      }
    ]
  },
  {
    "id": "sg-togg-upper",
    "label": "Upper Toggenburg",
    "group": "Eastern Switzerland",
    "anchors": [
      "Nesslau",
      "Neu St. Johann",
      "Wildhaus",
      "Alt St. Johann",
      "Unterwasser"
    ],
    "parentPackId": "gsw-toggenburg",
    "sourceIds": [
      "toggenburg",
      "sds"
    ],
    "variants": [
      {
        "id": "gsw-toggenburg-rest-1",
        "text": "Etz isch Ziit för e Pause. Alles andere chonnt nochher."
      }
    ]
  },
  {
    "id": "sg-sargans",
    "label": "Sarganserland",
    "group": "Eastern Switzerland",
    "anchors": [
      "Sargans",
      "Mels",
      "Flums",
      "Walenstadt",
      "Bad Ragaz",
      "Vilters",
      "Pfäfers"
    ],
    "parentPackId": "gsw-southeast",
    "sourceIds": [
      "sds"
    ],
    "variants": []
  },
  {
    "id": "sg-see-gaster",
    "label": "See-Gaster",
    "group": "Eastern Switzerland",
    "anchors": [
      "Rapperswil-Jona",
      "Uznach",
      "Schänis",
      "Kaltbrunn",
      "Amden",
      "Weesen"
    ],
    "parentPackId": "gsw-southeast",
    "sourceIds": [
      "sds"
    ],
    "variants": []
  },
  {
    "id": "tg-west",
    "label": "Western Thurgau candidate cluster",
    "group": "Eastern Switzerland",
    "anchors": [
      "Frauenfeld",
      "Diessenhofen",
      "Steckborn"
    ],
    "parentPackId": "gsw-thurgau",
    "sourceIds": [
      "thurgau"
    ],
    "variants": [
      {
        "id": "gsw-tg-west-rest-1",
        "text": "Nüüt pressiert. Do chasch e chli verwiile."
      }
    ]
  },
  {
    "id": "tg-east",
    "label": "Eastern Thurgau candidate cluster",
    "group": "Eastern Switzerland",
    "anchors": [
      "Arbon",
      "Romanshorn",
      "Amriswil",
      "Bischofszell"
    ],
    "parentPackId": "gsw-thurgau",
    "sourceIds": [
      "thurgau"
    ],
    "variants": [
      {
        "id": "gsw-tg-east-rest-1",
        "text": "Nünt pressiert. Hock ab und mach e chli Pause."
      }
    ]
  },
  {
    "id": "tg-hinter",
    "label": "Hinterthurgau",
    "group": "Eastern Switzerland",
    "anchors": [
      "Münchwilen",
      "Sirnach",
      "Eschlikon",
      "Aadorf"
    ],
    "parentPackId": "gsw-thurgau",
    "sourceIds": [
      "thurgau"
    ],
    "variants": []
  },
  {
    "id": "tg-seerhein-traditional",
    "label": "Traditional Untersee / Seerhein local voice",
    "group": "Eastern Switzerland",
    "anchors": [
      "Ermatingen",
      "Triboltingen",
      "Salenstein"
    ],
    "parentPackId": "gsw-thurgau",
    "sourceIds": [
      "thurgau"
    ],
    "variants": [
      {
        "id": "gsw-tg-seerhein-traditional-rest-1",
        "text": "Hock ab und mach e chlääni Pause."
      }
    ]
  },
  {
    "id": "tg-transition",
    "label": "Central Thurgau / Kreuzlingen transition",
    "group": "Eastern Switzerland",
    "anchors": [
      "Weinfelden",
      "Kreuzlingen",
      "Berg TG"
    ],
    "parentPackId": "gsw-thurgau",
    "sourceIds": [
      "thurgau"
    ],
    "variants": []
  },
  {
    "id": "ai-core",
    "label": "Appenzell Innerrhoden core",
    "group": "Eastern Switzerland",
    "anchors": [
      "Appenzell",
      "Schwende",
      "Rüte",
      "Gonten",
      "Schlatt",
      "Haslen"
    ],
    "parentPackId": "gsw-appenzell",
    "sourceIds": [
      "appenzell-ai",
      "appenzell-tourism"
    ],
    "variants": [
      {
        "id": "gsw-appenzell-ai-rest-1",
        "text": "Chnooze chasch denn wider. Etz mach e bezli Pause."
      }
    ]
  },
  {
    "id": "ai-oberegg",
    "label": "Oberegg contact / exclave",
    "group": "Eastern Switzerland",
    "anchors": [
      "Oberegg"
    ],
    "parentPackId": "gsw-appenzell",
    "sourceIds": [
      "sds",
      "appenzell-literature"
    ],
    "variants": []
  },
  {
    "id": "ar-hinter",
    "label": "Ausserrhoden Hinterland",
    "group": "Eastern Switzerland",
    "anchors": [
      "Herisau",
      "Waldstatt",
      "Schwellbrunn",
      "Urnäsch",
      "Hundwil",
      "Schönengrund"
    ],
    "parentPackId": "gsw-appenzell",
    "sourceIds": [
      "sds",
      "appenzell-ar",
      "appenzell-literature"
    ],
    "variants": [
      {
        "id": "gsw-appenzell-ar-literary-rest-1",
        "text": "Sonnesiits oder schattehalb: Mach e chli Pause."
      }
    ]
  },
  {
    "id": "ar-mittel",
    "label": "Ausserrhoden Mittelland",
    "group": "Eastern Switzerland",
    "anchors": [
      "Teufen",
      "Bühler",
      "Gais",
      "Speicher",
      "Trogen"
    ],
    "parentPackId": "gsw-appenzell",
    "sourceIds": [
      "sds",
      "appenzell-ar",
      "appenzell-literature"
    ],
    "variants": [
      {
        "id": "gsw-appenzell-ar-literary-rest-1",
        "text": "Sonnesiits oder schattehalb: Mach e chli Pause."
      }
    ]
  },
  {
    "id": "ar-vorder",
    "label": "Ausserrhoden Vorderland",
    "group": "Eastern Switzerland",
    "anchors": [
      "Heiden",
      "Wolfhalden",
      "Walzenhausen",
      "Reute AR",
      "Grub AR",
      "Lutzenberg",
      "Rehetobel",
      "Wald AR"
    ],
    "parentPackId": "gsw-appenzell",
    "sourceIds": [
      "sds",
      "appenzell-ar",
      "appenzell-literature"
    ],
    "variants": [
      {
        "id": "gsw-appenzell-ar-literary-rest-1",
        "text": "Sonnesiits oder schattehalb: Mach e chli Pause."
      }
    ]
  },
  {
    "id": "vs-goms",
    "label": "Goms",
    "group": "Wallis",
    "anchors": [
      "Münster VS",
      "Reckingen",
      "Fiesch",
      "Ernen"
    ],
    "parentPackId": "gsw-wallis",
    "sourceIds": [
      "wallis-regions",
      "wallis-lexicon",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "vs-brig",
    "label": "Brig / eastern main-valley contact",
    "group": "Wallis",
    "anchors": [
      "Brig",
      "Naters",
      "Termen"
    ],
    "parentPackId": "gsw-wallis",
    "sourceIds": [
      "wallis-regions",
      "wallis-lexicon",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "vs-visp-contact",
    "label": "Visp / surrounding contact area",
    "group": "Wallis",
    "anchors": [
      "Visp",
      "Baltschieder",
      "Eggerberg",
      "Ausserberg"
    ],
    "parentPackId": "gsw-wallis",
    "sourceIds": [
      "wallis-regions",
      "wallis-lexicon",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "vs-west",
    "label": "Western Upper Valais main valley",
    "group": "Wallis",
    "anchors": [
      "Raron",
      "Leuk",
      "Salgesch"
    ],
    "parentPackId": "gsw-wallis",
    "sourceIds": [
      "wallis-regions",
      "wallis-lexicon",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "vs-loetschen",
    "label": "Lötschental",
    "group": "Wallis",
    "anchors": [
      "Ferden",
      "Kippel",
      "Wiler",
      "Blatten"
    ],
    "parentPackId": "gsw-wallis",
    "sourceIds": [
      "wallis-regions",
      "wallis-lexicon",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "vs-saastal",
    "label": "Saastal",
    "group": "Wallis",
    "anchors": [
      "Saas-Fee",
      "Saas-Grund",
      "Saas-Almagell",
      "Saas-Balen"
    ],
    "parentPackId": "gsw-wallis",
    "sourceIds": [
      "wallis-regions",
      "wallis-lexicon",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "vs-mattertal",
    "label": "Mattertal / Zermatt",
    "group": "Wallis",
    "anchors": [
      "St. Niklaus",
      "Randa",
      "Täsch",
      "Zermatt"
    ],
    "parentPackId": "gsw-wallis",
    "sourceIds": [
      "wallis-regions",
      "wallis-lexicon",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "vs-simplon",
    "label": "Simplon / Gondo",
    "group": "Wallis",
    "anchors": [
      "Simplon Dorf",
      "Gondo"
    ],
    "parentPackId": "gsw-wallis",
    "sourceIds": [
      "wallis-regions",
      "wallis-lexicon",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-chur",
    "label": "Chur / lower Chur Rhine valley",
    "group": "German Graubünden",
    "anchors": [
      "Chur",
      "Felsberg",
      "Trimmis",
      "Zizers"
    ],
    "parentPackId": "gsw-buendner",
    "sourceIds": [
      "sds",
      "buendner-word"
    ],
    "variants": [
      {
        "id": "gsw-buendner-rhine-rest-1",
        "text": "Do chasch a Wili patschifig dasitza."
      }
    ]
  },
  {
    "id": "gr-landquart",
    "label": "Landquart / Bündner Herrschaft",
    "group": "German Graubünden",
    "anchors": [
      "Landquart",
      "Malans",
      "Maienfeld",
      "Jenins",
      "Fläsch"
    ],
    "parentPackId": "gsw-buendner",
    "sourceIds": [
      "sds",
      "buendner-word"
    ],
    "variants": [
      {
        "id": "gsw-buendner-rhine-rest-1",
        "text": "Do chasch a Wili patschifig dasitza."
      }
    ]
  },
  {
    "id": "gr-praettigau",
    "label": "Prättigau",
    "group": "German Graubünden",
    "anchors": [
      "Schiers",
      "Luzein",
      "St. Antönien",
      "Küblis",
      "Klosters"
    ],
    "parentPackId": "gsw-buendner",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-davos",
    "label": "Davos",
    "group": "German Graubünden",
    "anchors": [
      "Davos",
      "Monstein",
      "Wiesen GR"
    ],
    "parentPackId": "gsw-buendner",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-schanfigg",
    "label": "Upper Schanfigg / local Walser traditions",
    "group": "German Graubünden",
    "anchors": [
      "Langwies",
      "Arosa",
      "Peist",
      "Tschiertschen"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-vals",
    "label": "Vals",
    "group": "German Graubünden",
    "anchors": [
      "Vals"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-safien",
    "label": "Safiental",
    "group": "German Graubünden",
    "anchors": [
      "Safien Platz",
      "Thalkirch",
      "Tenna"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-rheinwald",
    "label": "Rheinwald",
    "group": "German Graubünden",
    "anchors": [
      "Splügen",
      "Hinterrhein",
      "Nufenen",
      "Sufers"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-avers",
    "label": "Avers",
    "group": "German Graubünden",
    "anchors": [
      "Juf",
      "Cresta Avers",
      "Madris"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-obersaxen",
    "label": "Obersaxen German localities",
    "group": "German Graubünden",
    "anchors": [
      "Obersaxen",
      "Meierhof",
      "Affeier"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-tschappina",
    "label": "Tschappina",
    "group": "German Graubünden",
    "anchors": [
      "Tschappina",
      "Obertschappina"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-mutten",
    "label": "Mutten",
    "group": "German Graubünden",
    "anchors": [
      "Mutten",
      "Obermutten"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "walser",
      "walser-books",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "gr-samnaun",
    "label": "Samnaunerisch: South Bavarian / Tyrolean",
    "group": "German Graubünden",
    "anchors": [
      "Samnaun",
      "Ravaisch",
      "Laret",
      "Compatsch",
      "Plan Samnaun"
    ],
    "parentPackId": "bar-samnaun",
    "sourceIds": [
      "samnaun"
    ],
    "variants": []
  },
  {
    "id": "ti-bosco-gurin",
    "label": "Gurinerdeutsch / Ggurijnartitsch",
    "group": "German Graubünden",
    "anchors": [
      "Bosco Gurin"
    ],
    "parentPackId": "gsw-walser",
    "sourceIds": [
      "bosco",
      "walser"
    ],
    "variants": []
  },
  {
    "id": "rm-sursilvan",
    "label": "Sursilvan written idiom",
    "group": "Romansh",
    "anchors": [
      "Ilanz/Glion",
      "Trun",
      "Disentis/Mustér",
      "Sumvitg",
      "Breil/Brigels",
      "Lumnezia",
      "Laax",
      "Falera"
    ],
    "parentPackId": "rm-sursilvan",
    "sourceIds": [
      "romansh",
      "romansh-regions"
    ],
    "variants": []
  },
  {
    "id": "rm-tuatschin",
    "label": "Tuatschin spoken / Sursilvan written tradition",
    "group": "Romansh",
    "anchors": [
      "Tujetsch",
      "Sedrun"
    ],
    "parentPackId": "rm-sursilvan",
    "sourceIds": [
      "romansh",
      "romansh-regions"
    ],
    "variants": []
  },
  {
    "id": "rm-sutsilvan",
    "label": "Sutsilvan written idiom",
    "group": "Romansh",
    "anchors": [
      "Zillis/Reischen",
      "Andeer",
      "Mathon",
      "Lohn GR",
      "Donat"
    ],
    "parentPackId": "rm-sutsilvan",
    "sourceIds": [
      "romansh",
      "romansh-regions"
    ],
    "variants": []
  },
  {
    "id": "rm-surmiran",
    "label": "Surmiran written idiom",
    "group": "Romansh",
    "anchors": [
      "Savognin",
      "Riom",
      "Parsonz",
      "Tinizong",
      "Cunter",
      "Tiefencastel",
      "Lantsch/Lenz",
      "Vaz/Obervaz"
    ],
    "parentPackId": "rm-surmiran",
    "sourceIds": [
      "romansh",
      "romansh-regions"
    ],
    "variants": []
  },
  {
    "id": "rm-puter",
    "label": "Puter written idiom",
    "group": "Romansh",
    "anchors": [
      "Samedan",
      "Zuoz",
      "Celerina/Schlarigna",
      "Pontresina",
      "Bever",
      "La Punt",
      "Madulain",
      "S-chanf",
      "Sils/Segl",
      "Silvaplana",
      "St. Moritz"
    ],
    "parentPackId": "rm-puter",
    "sourceIds": [
      "romansh",
      "romansh-regions"
    ],
    "variants": []
  },
  {
    "id": "rm-bergun",
    "label": "Bargunsegner spoken / Puter written tradition",
    "group": "Romansh",
    "anchors": [
      "Bergün/Bravuogn"
    ],
    "parentPackId": "rm-puter",
    "sourceIds": [
      "romansh-regions"
    ],
    "variants": []
  },
  {
    "id": "rm-vallader",
    "label": "Vallader written idiom",
    "group": "Romansh",
    "anchors": [
      "Scuol",
      "Sent",
      "Ftan",
      "Ardez",
      "Guarda",
      "Zernez",
      "Susch",
      "Lavin",
      "Tschlin",
      "Ramosch"
    ],
    "parentPackId": "rm-vallader",
    "sourceIds": [
      "romansh",
      "romansh-regions"
    ],
    "variants": []
  },
  {
    "id": "rm-jauer",
    "label": "Jauer spoken / Vallader written tradition",
    "group": "Romansh",
    "anchors": [
      "Tschierv",
      "Fuldera",
      "Lü",
      "Valchava",
      "Santa Maria Val Müstair",
      "Müstair"
    ],
    "parentPackId": "rm-vallader",
    "sourceIds": [
      "romansh",
      "romansh-regions"
    ],
    "variants": []
  },
  {
    "id": "gr-bivio-contact",
    "label": "Bivio/Beiva multilingual contact",
    "group": "Romansh",
    "anchors": [
      "Bivio/Beiva"
    ],
    "parentPackId": "rm-surmiran",
    "sourceIds": [
      "romansh-regions",
      "cde"
    ],
    "variants": []
  },
  {
    "id": "gr-rhine-rm-contact",
    "label": "Chur Rhine-valley / Domleschg Romansh–German contact",
    "group": "Romansh",
    "anchors": [
      "Domat/Ems",
      "Rhäzüns",
      "Bonaduz",
      "Domleschg",
      "Heinzenberg"
    ],
    "parentPackId": "rm-sutsilvan",
    "sourceIds": [
      "romansh",
      "sds"
    ],
    "variants": []
  },
  {
    "id": "fr-vaud",
    "label": "Regional French: Vaud",
    "group": "Romandie",
    "anchors": [
      "Lausanne",
      "Yverdon-les-Bains",
      "Nyon",
      "Montreux"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "gpsr"
    ],
    "variants": []
  },
  {
    "id": "fr-geneva",
    "label": "Regional French: Geneva",
    "group": "Romandie",
    "anchors": [
      "Genève",
      "Carouge"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "gpsr"
    ],
    "variants": []
  },
  {
    "id": "fr-fribourg",
    "label": "Regional French: French-speaking Fribourg",
    "group": "Romandie",
    "anchors": [
      "Bulle",
      "Romont",
      "Châtel-Saint-Denis"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr"
    ],
    "variants": []
  },
  {
    "id": "fr-valais",
    "label": "Regional French: French-speaking Valais",
    "group": "Romandie",
    "anchors": [
      "Sion",
      "Sierre",
      "Martigny",
      "Monthey"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr"
    ],
    "variants": []
  },
  {
    "id": "fr-neuchatel",
    "label": "Regional French: Neuchâtel",
    "group": "Romandie",
    "anchors": [
      "Neuchâtel",
      "La Chaux-de-Fonds",
      "Le Locle"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "gpsr"
    ],
    "variants": []
  },
  {
    "id": "fr-jura",
    "label": "Regional French: Jura and Bernese Jura",
    "group": "Romandie",
    "anchors": [
      "Delémont",
      "Porrentruy",
      "Saignelégier",
      "Moutier",
      "Tavannes",
      "Saint-Imier",
      "Tramelan",
      "La Neuveville"
    ],
    "parentPackId": "frc-jura",
    "sourceIds": [
      "gpsr",
      "moutier"
    ],
    "variants": []
  },
  {
    "id": "frp-vaud-alps",
    "label": "Vaud Alpine Francoprovençal traditions",
    "group": "Romandie",
    "anchors": [
      "Ormont-Dessus",
      "Ormont-Dessous",
      "Château-d’Œx",
      "Rougemont"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-fribourg-gruyere",
    "label": "Gruyère Francoprovençal traditions",
    "group": "Romandie",
    "anchors": [
      "Bulle",
      "Gruyères",
      "Val-de-Charmey"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-fribourg-broye",
    "label": "Broye Francoprovençal traditions",
    "group": "Romandie",
    "anchors": [
      "Estavayer",
      "Payerne"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-fribourg-veveyse",
    "label": "Veveyse Francoprovençal traditions",
    "group": "Romandie",
    "anchors": [
      "Châtel-Saint-Denis",
      "Attalens"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-valais-evolene",
    "label": "Evolène patois",
    "group": "Romandie",
    "anchors": [
      "Evolène",
      "Les Haudères"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-valais-nendaz",
    "label": "Nendaz patois",
    "group": "Romandie",
    "anchors": [
      "Nendaz"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-valais-bagnes",
    "label": "Bagnes patois",
    "group": "Romandie",
    "anchors": [
      "Le Châble",
      "Lourtier",
      "Bruson"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-valais-entremont",
    "label": "Entremont local patois",
    "group": "Romandie",
    "anchors": [
      "Orsières",
      "Liddes",
      "Bourg-Saint-Pierre"
    ],
    "parentPackId": "frp-alpine",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-geneva-historical",
    "label": "Geneva historical Francoprovençal",
    "group": "Romandie",
    "anchors": [
      "Genève",
      "Meyrin"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "frp-neuchatel-historical",
    "label": "Neuchâtel historical Francoprovençal",
    "group": "Romandie",
    "anchors": [
      "Val-de-Ruz",
      "Val-de-Travers"
    ],
    "parentPackId": "frp-west",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "oil-jura-ajoie",
    "label": "Jurassian / Franc-Comtois: Ajoie",
    "group": "Romandie",
    "anchors": [
      "Porrentruy",
      "Courgenay",
      "Boncourt"
    ],
    "parentPackId": "frc-jura",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "oil-jura-clos-doubs",
    "label": "Jurassian / Franc-Comtois: Clos du Doubs",
    "group": "Romandie",
    "anchors": [
      "Saint-Ursanne",
      "Soubey"
    ],
    "parentPackId": "frc-jura",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "oil-jura-franches-montagnes",
    "label": "Jurassian / Franc-Comtois: Franches-Montagnes",
    "group": "Romandie",
    "anchors": [
      "Saignelégier",
      "Le Noirmont",
      "Les Breuleux"
    ],
    "parentPackId": "frc-jura",
    "sourceIds": [
      "gpsr",
      "romand-historical"
    ],
    "variants": []
  },
  {
    "id": "lmo-mendrisiotto",
    "label": "Mendrisiotto Lombard",
    "group": "Italian Switzerland",
    "anchors": [
      "Mendrisio",
      "Chiasso",
      "Balerna",
      "Stabio"
    ],
    "parentPackId": "lmo-lowland",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-luganese",
    "label": "Luganese Lombard",
    "group": "Italian Switzerland",
    "anchors": [
      "Lugano",
      "Massagno",
      "Paradiso",
      "Morcote"
    ],
    "parentPackId": "lmo-lowland",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-malcantone",
    "label": "Malcantone local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Agno",
      "Bioggio",
      "Novaggio",
      "Astano"
    ],
    "parentPackId": "lmo-lowland",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-bellinzonese",
    "label": "Bellinzonese local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Bellinzona",
      "Giubiasco",
      "Sementina"
    ],
    "parentPackId": "lmo-prealpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-locarnese",
    "label": "Locarnese local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Locarno",
      "Minusio",
      "Ascona",
      "Muralto"
    ],
    "parentPackId": "lmo-prealpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-vallemaggia",
    "label": "Vallemaggia local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Maggia",
      "Cevio",
      "Lavizzara",
      "Avegno"
    ],
    "parentPackId": "lmo-alpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-leventina",
    "label": "Leventina local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Airolo",
      "Ambrì",
      "Faido",
      "Giornico"
    ],
    "parentPackId": "lmo-alpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-bedretto",
    "label": "Bedretto",
    "group": "Italian Switzerland",
    "anchors": [
      "Bedretto",
      "Villa Bedretto"
    ],
    "parentPackId": "lmo-alpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-blenio",
    "label": "Blenio local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Acquarossa",
      "Olivone",
      "Malvaglia"
    ],
    "parentPackId": "lmo-alpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-mesolcina",
    "label": "Mesolcina local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Roveredo GR",
      "Grono",
      "Lostallo",
      "Soazza",
      "Mesocco"
    ],
    "parentPackId": "lmo-prealpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-calanca",
    "label": "Calanca local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Arvigo",
      "Braggio",
      "Rossa"
    ],
    "parentPackId": "lmo-prealpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-bregaglia",
    "label": "Bregagliot local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Vicosoprano",
      "Stampa",
      "Bondo",
      "Soglio",
      "Castasegna"
    ],
    "parentPackId": "lmo-prealpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  },
  {
    "id": "lmo-poschiavo",
    "label": "Poschiavino local varieties",
    "group": "Italian Switzerland",
    "anchors": [
      "Poschiavo",
      "Le Prese",
      "Brusio"
    ],
    "parentPackId": "lmo-prealpine",
    "sourceIds": [
      "cde"
    ],
    "variants": []
  }
] as const;
export const DIALECT_DATA_VERSION = "catalogue-1.0.0-2026-09-12";
