nodeName: blizzard
existingSecret: benchly-secrets

images:
  web: ghcr.io/busykoala/b-nkliapp@sha256:80f8b9359404efbd789f3a60aa9b843d9a491c9d1d702b7539973681dfe2c987
  worker: ghcr.io/busykoala/b-nkliapp@sha256:2975fa6b5fe24a772ebe9af6305f47321dec8c0bd46d7fd29489a7ebd3b0b85c
  test: curlimages/curl:8.16.0

storage:
  className: benchly-local
  root: /srv/data/benchly/data
  size: 50Gi

host: xn--bnkliapp-0za.ch
gateway:
  name: blizzard
  namespace: gateway-system
  listener: https-5

web:
  walkingRouterUrl: http://graphhopper.routing.svc.cluster.local:8989
  aiLabelsEnabled: auto
  verificationThreshold: 3
  resources:
    requests: {cpu: 250m, memory: 512Mi}
    limits: {cpu: "2", memory: 4Gi}

workers:
  temporaryStorage: 120Gi
  visionModel: benchly-vision
