apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: inference
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.listener }}
  hostnames: [{{ .Values.host | quote }}]
  rules:
    - timeouts:
        request: 2h
        backendRequest: 2h
      backendRefs:
        - name: inference-api
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: inference-http-redirect
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: http
  hostnames: [{{ .Values.host | quote }}]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
