apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.className }}
  local:
    path: {{ .Values.storage.root }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [{{ .Values.nodeName }}]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.storage.className }}
  volumeName: {{ .Release.Name }}-data
  resources:
    requests:
      storage: {{ .Values.storage.size }}
